### ISSUE TITLE
Package not working on Laravel 5.8, Php 7.2, Elasticsearch 7.2.1

### ISSUE THREAD

**Issue by oknoote** [babenkoivan/scout-elasticsearch-driver#331]
**Versions**

- scout-elastic-driver: 4.0.1
- laravel/framwork: 5.8
- php: 7.2.27
- elasticsearch: 7.2.1

**Description**

When I try to create an index using the following command on the command line:
`php artisan elastic:create-index App\\UserIndexConfigurator`

I get the following error:
```
In Connection.php line 702:
                                                                                                                 
  Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $c  
  ode [, Throwable $previous = NULL]]])    
```

I get the same issue when simply saving a model that implements uses ScoutElastic\Searchable.

**Steps to reproduce**

Make sure ES is running
`$ curl -X GET 127.0.0.1:9200`
Response:
```
{
  "name" : "jubilant-feather",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_na_",
  "version" : {
    "number" : "7.2.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "fe6cb20",
    "build_date" : "2019-07-24T17:58:29.979462Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

The contents of my UserIndexConfigurator.php file:
```
<?php
namespace App;

use ScoutElastic\IndexConfigurator;

class UserIndexConfigurator extends IndexConfigurator
{
    protected $name = 'user_index';

    // You can specify any settings you want, for example, analyzers.
    protected $settings = [
        'analysis' => [
            'analyzer' => [
                'en_std' => [
                    'type' => 'standard',
                    'stopwords' => '_english_'
                ]
            ]
        ]
    ];
}
```

At the top of the User.php file:
`use ScoutElastic\Searchable;`

Inside the User class:
```
use Searchable
protected $indexConfigurator = UserIndexConfigurator::class;
```

Locally I am running Homestead with PHP7.4 and ElasticSearch 7.5 and was not running into any issues.

I started on my VPS with those versions as well but started downgrading to PHP7.2 and ES7.2 to see if this would make a difference on my cloud VPS running Ubuntu 18.04 but with no help.

**Comment by oknoote** [comment]
Examining the log file for this cluster under /var/log/elasticsearch I repeatedly see the following message:
```
[2020-02-05T15:21:06,626][WARN ][o.e.c.c.ClusterFormationFailureHelper] [jubilant-feather] master not discovered yet, this node has not previously joined a bootstrapped (v7+)
 cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered []; discovery will continue using [[::1]:9300] from hosts providers and [{jubilant-feather
}{hqecfqY-Riue47gy0tsoUQ}{207cLf1uS-Gnd6rd3aozew}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=3147321344, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster
 state; node term 0, last-accepted version 0 in term 0
```

Hence I'm posting my elasticsearch.yml file here as well as this might be relevant:
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: myclustername
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: mynode
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 127.0.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.seed_hosts: ["127.0.0.1", "[::1]"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
```

**Comment by oknoote** [comment]
And this pops up in the logs when I try to create the user_index index using the elastic:create-index command:
```
[2020-02-05T15:29:10,161][DEBUG][o.e.a.a.i.c.TransportCreateIndexAction] [jubilant-feather] timed out while retrying [indices:admin/create] after failure (timeout [30s])
[2020-02-05T15:29:10,163][WARN ][r.suppressed             ] [jubilant-feather] path: /user_index, params: {index=user_index}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.onTimeout(TransportMasterNodeAction.java:251) [elasticsearch-7.2.1.jar:7.2.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.2.1.jar:7.2.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.2.1.jar:7.2.1]
        at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572) [elasticsearch-7.2.1.jar:7.2.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) [elasticsearch-7.2.1.jar:7.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by oknoote** [comment]
I managed to resolve this by commenting the following line in Elasticsearch.yml:

`discovery.seed_hosts: ["127.0.0.1", "[::1]"]`

This was required in Homestead but not for the (single node) cluster I am running now, with 127.0.0.1 as the network.host!
